services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=mydb
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - database

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
