services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - UPLOAD_DIR=${UPLOAD_DIR}
    depends_on:
      - database

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streaum
      MYSQL_USER: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
