name: Docker CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: docker-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t streaum:ci .

      - name: Run container (random host port)
        run: docker run -d -P --name streaum streaum:ci

      - name: Get mapped port
        id: port
        shell: bash
        run: |
          MAP=$(docker port streaum 8080/tcp || true)
          echo "docker port output: $MAP"
          if [ -z "$MAP" ]; then
            echo "Failed to discover mapped port"
            docker logs streaum || true
            exit 1
          fi
          PORT=$(echo "$MAP" | sed -E 's/.*:([0-9]+)/\1/')
          echo "PORT=$PORT" >> "$GITHUB_OUTPUT"

      - name: Wait for app to be ready
        env:
          PORT: ${{ steps.port.outputs.PORT }}
        shell: bash
        run: |
          echo "Waiting for http://127.0.0.1:${PORT}/ ..."
          for i in {1..60}; do
            # Fail only on 4xx/5xx; 2xx/3xx are OK
            if curl -fsS "http://127.0.0.1:${PORT}/" -o /dev/null; then
              echo "App is responding."
              exit 0
            fi

            # If the container died, bail out and show logs
            if ! docker ps --filter "name=streaum" --filter "status=running" --format '{{.Names}}' | grep -q '^streaum$'; then
              echo "Container exited unexpectedly. Logs:"
              docker logs streaum || true
              exit 1
            fi

            sleep 2
          done

          echo "Timed out waiting for app to respond."
          docker logs streaum || true
          exit 1

      - name: Smoke test root endpoint
        env:
          PORT: ${{ steps.port.outputs.PORT }}
        shell: bash
        run: |
          STATUS=$(curl -sS -o /dev/null -w '%{http_code}' "http://127.0.0.1:${PORT}/")
          echo "HTTP status: $STATUS"
          # Accept 2xx and 3xx as success
          if [ "$STATUS" -lt 200 ] || [ "$STATUS" -ge 400 ]; then
            echo "Unexpected HTTP status from root endpoint."
            docker logs streaum || true
            exit 1
          fi

      - name: Show logs on failure
        if: failure()
        run: docker logs streaum || true

      - name: Cleanup
        if: always()
        run: docker rm -f streaum || true